### ISSUE TITLE
Repo boş ?

### ISSUE THREAD

**Issue by alperyazar** [yunusesergun/yesergun.fpga.dev#5]
![image](https://github.com/user-attachments/assets/8f185d5d-a958-45ad-a377-4547c5935949)

Branch ayrıymış ama yine de bunu açmak istiyorum.

**Comment by yunusesergun** [comment]
Abi review bitmeden master'a merge etmiyim demiştim. Invitation'ı kabul etmeden de seni tagleyemedim. Ama sen zaten farkındasın. Bu issue'yu kapıyorum o zaman :D
